version: '3'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: spotify_favorites
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  api:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

volumes:
  redis:
    driver: local
  db:
    driver: local
